import { drizzle } from 'drizzle-orm/postgres-js';
import { pgTable, serial, varchar } from 'drizzle-orm/pg-core';
import {
  bigserial,
  bigint,
  integer,
  json,
  text,
  timestamp,
} from 'drizzle-orm/pg-core';
import { and, asc, desc, eq, sql } from 'drizzle-orm';
import postgres from 'postgres';
import { genSaltSync, hashSync } from 'bcrypt-ts';

let client = postgres(`${process.env.POSTGRES_URL!}?sslmode=require`);
let db = drizzle(client);

export async function getUser(email: string) {
  const users = await ensureTableExists();
  return await db.select().from(users).where(eq(users.email, email));
}

export async function createUser(email: string, password: string) {
  const users = await ensureTableExists();
  let salt = genSaltSync(10);
  let hash = hashSync(password, salt);

  return await db.insert(users).values({ email, password: hash });
}

async function ensureTableExists() {
  const result = await client`
    SELECT EXISTS (
      SELECT FROM information_schema.tables 
      WHERE table_schema = 'public' 
      AND table_name = 'User'
    );`;

  if (!result[0].exists) {
    await client`
      CREATE TABLE "User" (
        id SERIAL PRIMARY KEY,
        email VARCHAR(64),
        password VARCHAR(64)
      );`;
  }

  const table = pgTable('User', {
    id: serial('id').primaryKey(),
    email: varchar('email', { length: 64 }),
    password: varchar('password', { length: 64 }),
  });

  return table;
}

/* ------------------------------ 业务表 ------------------------------ */

// 已有表（words-admin 建于 Supabase），列名为带引号的驼峰标识符
export const books = pgTable('books', {
  id: bigserial('id', { mode: 'number' }).primaryKey(),
  title: varchar('title', { length: 255 }).notNull(),
  wordCount: integer('word_count').notNull().default(0),
  coverUrl: text('cover_url'),
  bookId: varchar('book_id', { length: 100 }).notNull(),
  tags: text('tags'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

// 驼峰列名（"wordRank"/"bookId"）由 drizzle 自动加引号保留大小写
export const words = pgTable('words', {
  id: bigserial('id', { mode: 'number' }).primaryKey(),
  wordRank: integer('wordRank'),
  headWord: text('headWord'),
  content: json('content'),
  bookId: text('bookId'),
});

export type Book = typeof books.$inferSelect;
export type Word = typeof words.$inferSelect;

/* --------------------------- 学习进度表 --------------------------- */

let studyProgressTable: ReturnType<typeof studyProgressBuilder> | null = null;

function studyProgressBuilder() {
  return pgTable('study_progress', {
    id: bigserial('id', { mode: 'number' }).primaryKey(),
    userId: bigint('user_id', { mode: 'number' }).notNull(),
    bookId: varchar('book_id', { length: 100 }).notNull(),
    lastWordRank: integer('last_word_rank').notNull().default(0),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  });
}

/** 建表兜底：study_progress 不存在时自动创建（与 User 表同一模式） */
async function ensureStudyProgressTable() {
  const result = await client`
    SELECT EXISTS (
      SELECT FROM information_schema.tables
      WHERE table_schema = 'public'
      AND table_name = 'study_progress'
    );`;

  if (!result[0].exists) {
    await client`
      CREATE TABLE study_progress (
        id bigint generated by default as identity not null,
        user_id bigint not null,
        book_id varchar(100) not null,
        last_word_rank integer not null default 0,
        created_at timestamptz not null default now(),
        updated_at timestamptz not null default now(),
        constraint study_progress_pkey primary key (id),
        constraint study_progress_user_book_unique unique (user_id, book_id)
      );`;
    await client`
      CREATE INDEX idx_study_progress_user_updated
        ON study_progress (user_id, updated_at DESC);`;
  }

  if (!studyProgressTable) {
    studyProgressTable = pgTable('study_progress', {
      id: bigserial('id', { mode: 'number' }).primaryKey(),
      userId: bigint('user_id', { mode: 'number' }).notNull(),
      bookId: varchar('book_id', { length: 100 }).notNull(),
      lastWordRank: integer('last_word_rank').notNull().default(0),
      createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
      updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
    });
  }

  return studyProgressTable;
}

/* --------------------------- 查询函数 --------------------------- */

export async function getBooks(): Promise<Book[]> {
  return await db.select().from(books).orderBy(asc(books.id));
}

export async function getBookByBookId(bookId: string): Promise<Book | undefined> {
  const rows = await db.select().from(books).where(eq(books.bookId, bookId)).limit(1);
  return rows[0];
}

/** 学习序列：wordRank 升序、null 排最后、id 兜底 */
export async function getWordsByBookId(bookId: string): Promise<Word[]> {
  return await db
    .select()
    .from(words)
    .where(eq(words.bookId, bookId))
    .orderBy(sql`${words.wordRank} asc nulls last`, asc(words.id));
}

export async function getWordById(id: number): Promise<Word | undefined> {
  const rows = await db.select().from(words).where(eq(words.id, id)).limit(1);
  return rows[0];
}

export type ProgressItem = {
  bookId: string;
  title: string;
  wordCount: number;
  lastWordRank: number;
  updatedAt: Date;
};

export async function getLatestProgress(userId: number): Promise<ProgressItem | undefined> {
  const sp = await ensureStudyProgressTable();
  const rows = await db
    .select({
      bookId: sp.bookId,
      title: books.title,
      wordCount: books.wordCount,
      lastWordRank: sp.lastWordRank,
      updatedAt: sp.updatedAt,
    })
    .from(sp)
    .innerJoin(books, eq(sp.bookId, books.bookId))
    .where(eq(sp.userId, userId))
    .orderBy(desc(sp.updatedAt))
    .limit(1);
  return rows[0];
}

export async function getProgressList(userId: number): Promise<ProgressItem[]> {
  const sp = await ensureStudyProgressTable();
  return await db
    .select({
      bookId: sp.bookId,
      title: books.title,
      wordCount: books.wordCount,
      lastWordRank: sp.lastWordRank,
      updatedAt: sp.updatedAt,
    })
    .from(sp)
    .innerJoin(books, eq(sp.bookId, books.bookId))
    .where(eq(sp.userId, userId))
    .orderBy(desc(sp.updatedAt));
}

export async function getProgress(
  userId: number,
  bookId: string,
): Promise<{ lastWordRank: number } | undefined> {
  const sp = await ensureStudyProgressTable();
  const rows = await db
    .select({ lastWordRank: sp.lastWordRank })
    .from(sp)
    .where(and(eq(sp.userId, userId), eq(sp.bookId, bookId)))
    .limit(1);
  return rows[0];
}

export async function upsertProgress(userId: number, bookId: string, wordRank: number) {
  const sp = await ensureStudyProgressTable();
  await db
    .insert(sp)
    .values({ userId, bookId, lastWordRank: wordRank })
    .onConflictDoUpdate({
      target: [sp.userId, sp.bookId],
      set: { lastWordRank: wordRank, updatedAt: new Date() },
    });
}

/* ------------------------- 学习卡片投影 ------------------------- */

export type StudyCard = {
  id: number; // words.id → 详情页路由
  wordRank: number | null;
  headWord: string | null;
  usphone: string | null;
  ukphone: string | null;
  tranCn: string | null; // trans[0].tranCn
  sContent: string | null; // sentences[0].sContent
  sCn: string | null; // sentences[0].sCn
  pContent: string | null; // 降级：phrases[0].pContent
  pCn: string | null; // 降级：phrases[0].pCn
};

export function toStudyCard(row: Word): StudyCard {
  const c = (row.content ?? null) as WordContent | null;
  return {
    id: row.id,
    wordRank: row.wordRank,
    headWord: row.headWord,
    usphone: c?.usphone ?? null,
    ukphone: c?.ukphone ?? null,
    tranCn: c?.trans?.[0]?.tranCn ?? null,
    sContent: c?.sentence?.sentences?.[0]?.sContent ?? null,
    sCn: c?.sentence?.sentences?.[0]?.sCn ?? null,
    pContent: c?.phrase?.phrases?.[0]?.pContent ?? null,
    pCn: c?.phrase?.phrases?.[0]?.pCn ?? null,
  };
}

/** words.content（content.word.content 子对象）的类型，字段可能缺失 */
export type WordContent = {
  usphone?: string;
  ukphone?: string;
  trans?: { tranCn?: string; tranOther?: string }[];
  sentence?: { sentences?: { sContent?: string; sCn?: string }[] };
  phrase?: { phrases?: { pContent?: string; pCn?: string }[] };
  syno?: { synos?: { pos?: string; tran?: string; hwds?: { w?: string }[] }[] };
  relWord?: { rels?: { pos?: string; words?: { hwd?: string; tran?: string }[] }[] };
  remMethod?: { val?: string };
};
